# Site settings
title: Solace Samples Javascript
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-javascript"
repository: https://github.com/SolaceSamples/solace-samples-javascript

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
advanced-samples: //github.com/SolaceSamples/solace-samples-javascript/tree/master/src/advanced-samples
links-community: //dev.solace.com/community/
links-downloads: //dev.solace.com/downloads/
links-get-started-javascript: //dev.solace.com/get-started/javascript-tutorials/
links-solaceCloud-setup: //cloud.solace.com/create-messaging-service/
links-tech-other: //dev.solace.com/tech/#other
docs-core-concepts: //docs.solace.com/Features/Core-Concepts.htm
docs-session-events: //docs.solace.com/Solace-Messaging-APIs/Creating-Client-Sessions-1.htm#Handle-Sess-Events
docs-api-reference: //docs.solace.com/API-Developer-Online-Ref-Documentation/js/index.html
docs-semp: //docs.solace.com/SEMP/Using-SEMP-to-Manage-and-Monitor-Routers.htm
docs-topic-mapping: //docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-dte: //docs.solace.com/Features/Endpoints.htm
docs-active-flow-indication: //docs.solace.com/Solace-PubSub-Messaging-APIs/Developer-Guide/Creating-Flows.htm#Active-Flow-Indication
